### ISSUE TITLE
Make WebView use TS

### ISSUE THREAD

**Issue by EstebanDalelR** [watermelontools/watermelon-vscode#302]
Currently,[ we use JS to write on the webview](https://github.com/watermelontools/wm-extension/blob/dev/media/main.js), but it's tiresome to do so.
We'd like for it to compile on publish from ts files.

**Comment by EstebanDalelR** [comment]
As per the [github pull requests extension](https://github.com/microsoft/vscode-pull-request-github), we have to bundle it before bundling the whole thing. It probably requires [a webpack file in the root](https://medium.com/younited-tech-blog/reactception-extending-vs-code-extension-with-webviews-and-react-12be2a5898fd).

It's also interesting if we can use React instead of plain Jquery.

**Comment by baristaGeek** [comment]
+1 for React. 3 months later we have a better idea of what's useful and what not to people. Therefore it's justifiable to evolve.

**Comment by EstebanDalelR** [comment]
Will close as stale
