### ISSUE TITLE
Watermelon Extension vs.code

### ISSUE THREAD

**Issue by bugalwena** [watermelontools/watermelon-vscode#511]
The watermelon extension has had an issue since first installed. It can't create content. I'm logged in with GitHub and have the correct email address. I get repeated messages to sign into the Watermelon extension, and I am, but it persists. I am at a loss, too, cause of my problem. A message to my account on vs. code says to sign in.

**Comment by EstebanDalelR** [comment]
Hello!
I will look at this shortly, but first I need to know what version of Watermelon do you have?

**Comment by bugalwena** [comment]
Hi, thanks I'm running Watermelon version 2.0.7. Looking at the  Changelog I installed Watermelon about a month ago. I feel I'm missing something here

**Comment by EstebanDalelR** [comment]
Will close as stale
