### ISSUE TITLE
Support for Linear

### ISSUE THREAD

**Issue by tomtastico** [watermelontools/watermelon-vscode#547]
Not sure if this is the right place to request this, but:

Would be great to have support for [Linear](https://linear.app/), not just Jira :)

**Comment by EstebanDalelR** [comment]
Sure thing!
It's in our roadmap, soon!

**Comment by EstebanDalelR** [comment]
hey @tomtastico 
We have added linear [to our app,](https://github.com/apps/watermelon-context) we will soon add it to the extension

**Comment by tomtastico** [comment]
Awesome! Looking forward to having it in the extension too :) 

Hijacking this issue: any plans for Confluence Pages for documentation, in addition to Notion? :D

**Comment by baristaGeek** [comment]
> Awesome! Looking forward to having it in the extension too :)
> 
> Hijacking this issue: any plans for Confluence Pages for documentation, in addition to Notion? :D

Hey @tomtastico actually we do. I just opened [an issue](https://github.com/watermelontools/watermelon-extension/issues/553) for adding a Confluence integration. With the recent changes in [our search engine](https://github.com/watermelontools/watermelon) we can now support Linear, Confluence and Notion.

**Comment by EstebanDalelR** [comment]
Yes, we now have confluence!

**Comment by EstebanDalelR** [comment]
@tomtastico  you're welcome to open a new issue, this has been solved
