### ISSUE TITLE
Confluence Integration

### ISSUE THREAD

**Issue by baristaGeek** [watermelontools/watermelon-vscode#553]
We've recently [added Confluence as a new integration to our API.](https://github.com/watermelontools/watermelon/pull/206), therefore we can now support Confluence in our VS Code extension. 

Similar to most integrations, I would suggest sending the title of the most relevant Pull Request as a search parameter to this API to see what it finds and then render the results both on our hover box and our treeview. Then, we can keep refining from there.

**Comment by EstebanDalelR** [comment]
Uh, this works

**Comment by EstebanDalelR** [comment]
Probably closed when we changed the APi
